### PR TITLE
Add intro to python

### PR DESCRIPTION
**Pull request by hargunanie**

### CODE REVIEW

**Review by KazMalhotra — CHANGES_REQUESTED** [review]
tl;dr: work with Harper

It's a good start, but please make it more beginner-friendly. I can see you trying to make it funnier like the "aw crud, just hurry up". However, (sorry about this), that's not funny. My sincere recommendation is to actually work with Harper, and have your diplomatic, information intro, with his funny stuff. Also, no need to mention C.

**Review by KazMalhotra — COMMENTED** [review]
This is better. I would recommend making it less specific (for example, don't mention anything about alarm clocks as that's not really python's use case.). I would add some applications of python (eg. AI). Also, work with Harper to make it funnier.

**Review by KazMalhotra — CHANGES_REQUESTED** [review]
Ok, first off, the small things. There are a few typos, for example, "*This makes it a great, **quick,,** language to learn.*", and "*used to **develope** AI interfaces today*". Also, you emailed me saying "*I do not know that much about python as AI, so I kind of guessed...*". I'm not trying to be harsh or anything, but whatever you do, **do not guess; do research.** While your mention of python's AI applications are not inaccurate, please do research and seek to understand what you're writing about, rather than just guessing. Also, I will reach out to @harperkdavis and ask him help you.

**Comment by hargunanie** [comment]
Okay. I mentioned some stuff about django and flask, but Harper still hasn't replied. When he does, I'll make another commit (hopefully funnier) and let you know.

**Review by KazMalhotra — APPROVED** [review]
This is really good. The few things I would change are: no need to put down lower level, compiled languages. They can be good too. It just depends on the application. Also, great job including the fun fact about instagram, and I would encourage you to add more things made with python.

**Pull request merged**
